name: MacOS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  macos-integration-tests:
    runs-on: macos-11.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add local bin to PATH
        run: |
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Install python package and dependencies
        run: |
          python3 -m venv ${HOME}/.venv
          source ${HOME}/.venv/bin/activate
          pip3 install -U pip wheel setuptools
          pip3 install -U -r requirements.txt -r requirements-dev.txt
          pip3 install -e .
      - name: Install multipass
        run: |
          brew install multipass
          sleep 10
          multipass launch --name test -vvvv
          multipass exec test echo hi
